spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
  data-locations: data.sql
  schema-locations: schema.sql

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

    show-sql: true