spring:
  output:
    ansi:
      enabled: always

  main:
    allow-circular-references: true

  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

  datasource:
    url: jdbc:h2:mem:maindb

  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
